title: "Kankakee Community College"
google-tag_key: 'GTM-KRL8533'
collections:
  posts:
    output: false
  alerts:
    output: false
  contacts:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    post_title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
- scope:
    path: ''
    type: alerts
  values:
    title: ''
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  KCC offers intercollegiate men's basketball, women's basketball, baseball, softball, men's soccer and volleyball. The Cavaliers compete in Region IV of the NJCAA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://athletics.kcc.edu" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
# include:
#   - "_pages"
#   - "_posts"

# Output posts with dates that havent happened (future posts):
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "/assets/adobe/*"
  - "gulp-tasks"
  - "athletics-bad-response-object-from-sheetsAPI-request.js"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

contacts_sports:
  baseball: Baseball
  men's basketball: Mens's Basketball
  soccer: Soccer
  women's basketball: Women's Basketball
  softball: Softball
  volleyball: Volleyball
  women's soccer: Women's Soccer

_comments:
  title: This is the page title. <br/>Please don't change page titles without talking to web services first. <br/> Changing the page title may affect search engine results.
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  sport: "# Value dictates which schedule is pulled: <br/>\"1\" = All sports <br/>\"2\" = Baseball <br/>\"3\" = Softball <br/>\"4\" = Volleyball <br/>\"5\" = Soccer <br/>\"6\" = Women's Basketball <br/>\"7\" = Men's Basketball"
  description: "Descriptions are seen by search engines like Google and displayed in search results."
  post_title: Create a unique title for your news post. <br/> Do NOT use curly braces "{ }" in post titles. <br/> Do NOT use the same post title for different posts.

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
